/**
 * This file is autogenerated by scaffold-stylus.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "../utils/scaffold-eth/contract";

const deployedContracts = {
  "421614": {
    mock_usdc: {
      address: "0x241f74fed26ad33fc5de7d3197d56f14824139da",
      txHash:
        "0x237cf5cc4455b8475589cda070837d80fce3603e7194787f29ea10bac7978810",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "InsufficientAllowance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "InsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "InvalidReceiver",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "allowance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
    },
    junta: {
      address: "0x66eb72055b8eba05fec5f221eb0c8b58814fb3a8",
      txHash:
        "0xe3cc1b6e025d1d471330f9f23d88d5428144fb2a5fe4d610cf9e7053ddd5fcdc",
      abi: [
        {
          inputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "CuotasAlDia",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          name: "JuntaCompleta",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          name: "JuntaNoExiste",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "NoEsMiembro",
          type: "error",
        },
        {
          inputs: [],
          name: "ParametrosInvalidos",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferenciaFallida",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          name: "TurnoNoVencido",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "nombre",
              type: "string",
            },
            {
              internalType: "address[]",
              name: "miembros",
              type: "address[]",
            },
            {
              internalType: "uint256",
              name: "cuota",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "periodo",
              type: "uint64",
            },
          ],
          name: "createJunta",
          outputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
          ],
          name: "cycleCoverage",
          outputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
          ],
          name: "deposit",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
          ],
          name: "distribute",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "member",
              type: "address",
            },
          ],
          name: "history",
          outputs: [
            {
              internalType: "int128",
              name: "",
              type: "int128",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "int128",
              name: "",
              type: "int128",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
          ],
          name: "juntaNombre",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
          ],
          name: "juntaParams",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
          ],
          name: "juntaState",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "member",
              type: "address",
            },
          ],
          name: "juntasDe",
          outputs: [
            {
              internalType: "uint32[]",
              name: "",
              type: "uint32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "member",
              type: "address",
            },
          ],
          name: "memberState",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
          ],
          name: "miembros",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "member",
              type: "address",
            },
          ],
          name: "reportDispute",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "token",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalJuntas",
          outputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "verifyIntegrity",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
    },
    score_engine: {
      address: "0x6b6f385246672c6eb8defb7c4debcb4f1bd45158",
      txHash:
        "0x0a9172021d6d174f993a1f4670fcb3590db287303d4bb5cee8de65f39edf85fd",
      abi: [
        {
          inputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "LecturaDeJuntaFallida",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "member",
              type: "address",
            },
          ],
          name: "computeScore",
          outputs: [
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "member",
              type: "address",
            },
          ],
          name: "isPositive",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "junta",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "member",
              type: "address",
            },
          ],
          name: "latestScore",
          outputs: [
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "minimoCiclos",
          outputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "modelHash",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "member",
              type: "address",
            },
          ],
          name: "recordScore",
          outputs: [
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "member",
              type: "address",
            },
          ],
          name: "scoreAndCredit",
          outputs: [
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "umbralPositivo",
          outputs: [
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
    },
    pool: {
      address: "0x9e1a4a0f4653457bf8c7032a78f6735489b67c75",
      txHash:
        "0x336e9061e327e4d46ed3386176282a9a7d0990b9921908f8c14049bd0f3461bc",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
          ],
          name: "CreditoSuspendido",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "LiquidezInsuficiente",
          type: "error",
        },
        {
          inputs: [],
          name: "MontoInvalido",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "NoTienePrestamoActivo",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "ScoreNoDisponible",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferenciaFallida",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "YaTienePrestamoActivo",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "monto",
              type: "uint256",
            },
          ],
          name: "depositLiquidity",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "liquidityStatus",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "member",
              type: "address",
            },
          ],
          name: "loanOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "repay",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "junta_id",
              type: "uint32",
            },
          ],
          name: "requestLoan",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "scoreEngine",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "token",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint16",
              name: "score",
              type: "uint16",
            },
          ],
          name: "tramo",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
